language: rust
rust:
  - 1.8.0
  - stable
  - beta
  - nightly 
matrix:
  allow_failures:
    - rust: nightly
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
  - [ $TRAVIS_RUST_VERSION != nightly ] || cargo bench
  - cargo doc
